title = "RustCon Asia 2019"
baseURL = "https://rustcon.asia"
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
favicon = "favicon.png"
googleAnalyticsId = "TODO"
chinese_tickets = "http://www.huodongxing.com/event/6479456003900"
english_tickets = "https://ti.to/cryptape/rustcon-asia"
cfp = "https://cfp.rustcon.asia/"

[params.dates]
start = "20 April"
end = "23 April"
year = "2019"

[params.locations.talks]
name = "Hyatt Regency Beijing Wangjing"
address = "Lei Shing Hong Center, 8 Guangshun South Street, Chaoyang District, Beijing, China"

[params.locations.workshops]
name = "大望京科技商务园区浦项中心A座"
address = "Tower A, POSCO Center, 13 Wangjing Science And Technology Business Park, Chaoyang District, Beijing"
url = "http://www.poscocenter.cn/en/bbs/board.php?bo_table=m03_05&wr_id=1"

[params.description]
brief = "Beijing"
long = "Join us for the first Rust Conference in Asia!"

[params.fonts]
sansserif = "Titillium Web"
monospace = "Inconsolata"

[params.logos]
white = "img/logos/logo-white.svg"
color = "img/logos/logo-black.svg"
black = "img/logos/logo-black.svg"
pingcap = "img/logos/pingcap.png"
baidu = "img/logos/baidu.png"
cryptape = "img/logos/cryptape.png"

[params.assets]
fontAwesomeVersion = "5.3.1"
js  = ["jquery-3.3.1", "anchor", "app"]
css = ["syntax"]

[params.socialmedia]
github  = "https://github.com/rustcon-asia/beijing-2019"

[[params.home.buttons]]
text = "Tickets / 门票"
link = "/tickets"

[[params.home.buttons]]
text = "Call for Proposals"
link = "https://cfp.rustcon.asia/"

[[params.home.buttons]]
text = "Blog"
link = "/blog"


[outputs]
home = ["HTML", "REDIRECTS"]

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[mediaTypes."text/netlify"]
delimiter = ""
